#image: carlonluca/qt-dev:6.0.4
image: 
  name: arnoldnico/ifte-ci:py3.10.4-tox-vedo-bookworm
#  name: arnoldnico/ifte-ci:py3.10.4-vedo-bullseye
  entrypoint: [ '/bin/bash', '-s' ]
 

 
stages:          # List of stages for jobs, and their order of execution
  - info
  - test
  - bye

before_script:
  - git submodule update --remote
  #- strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
  #- python3 -m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh
  - python3 -m pip install --progress-bar off --ignore-installed -r requirements.txt

information:
  stage: info
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:my_first_section\r\e[0printenv"
    - printenv
    - echo -e "\e[0Ksection_end:`date +%s`:my_first_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:my_second_section\r\e[0packages"
    - pip list
    - echo -e "\e[0Ksection_end:`date +%s`:my_first_section\r\e[0K"
    - python --version
    - python3 --version
    - which python3
    - which pip3
    - pyenv versions
    - whoami

#test_pytest:
#  stage: test
#  script:
#    - pytest tests/ --junitxml=pytest_report.xml
#  artifacts:
#    when: always
#    reports:
#      junit: pytest_report.xml

test_tox:
  stage: test
  script:
    - pyenv versions
    - tox
  #coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: junit-*.xml
#      coverage_report:
#        coverage_format: cobertura
#        path: coverage.xml


goodbye:
  stage: bye
  script:
    - echo Tests successfull. Goodbye!

#include:
#- template: Code-Quality.gitlab-ci.yml