image: kitware/vtk-for-ci

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  - apt-get install pip
  - git submodule update --remote
  - python -m pip install -r requirements.txt
  - python -m pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye