image: angryred/recap-vtk:1.0.2

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  #- apt-get install python3-pip
  - strip --remove-section=.note.ABI-tag libQt6Core.so.6.5.2
  - git submodule update --remote
  - pip install -r requirements.txt --user
  - pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye