image: python:3.10.4-alpine

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  #- apt-get install python3-pip
  - apk update && \
    apk upgrade && \

    apk add --update ca-certificates && \

  - apk add gnutls-dev zlib-dev yasm-dev lame-dev libogg-dev \
    x264-dev libvpx-dev libvorbis-dev x265-dev freetype-dev \
    libass-dev libwebp-dev rtmpdump-dev libtheora-dev opus-dev && \

  - apk add --no-cache --virtual .build-dependencies \
    build-base coreutils tar bzip2 x264 gnutls nasm && \
    wget -O- http://ffmpeg.org/releases/ffmpeg-3.3.2.tar.gz | tar xzC /tmp && \
    cd /tmp/ffmpeg-${FFMPEG_VERSION} && \
    ./configure --bindir="/usr/bin" \
                --enable-version3 \
                --enable-gpl \
                --enable-nonfree \
                --enable-small \
                --enable-libmp3lame \
                --enable-libx264 \
                --enable-libx265 \
                --enable-libvpx \
                --enable-libtheora \
                --enable-libvorbis \
                --enable-libopus \
                --enable-libass \
                --enable-libwebp \
                --enable-librtmp \
                --enable-postproc \
                --enable-avresample \
                --enable-libfreetype \
                --enable-gnutls \
                --disable-debug && \
    make && \
    make install && \
    make distclean && \
    cd $OLDPWD && \
    rm -rf /tmp/ffmpeg-${FFMPEG_VERSION} && \
    apk del --purge .build-dependencies && \
    rm -rf /var/cache/apk/*
  - git submodule update --remote
  - pip install -r requirements.txt --user
  - pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye