#image: arnoldnico/ifte-ci:py3.10.4-ffmpeg-buster
image: 
  #name: arnoldnico/ifte-ci:py3.10.4-vedo-bookworm
  name: python:3.10.4-bullseye
  entrypoint: [ '/bin/bash', '-s' ]

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  - python --version
  - pip --version
  - echo "deb http://deb.debian.org/debian bullseye-backports main contrib non-free" >> /etc/apt/sources.list
  - echo "deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install ffmpeg x264 libsm6 libxext6 libglib2.0-0 qt6-base-dev
#  - ls -lh /usr/local/bin
#  - ls -lh /usr/local/lib
#  - ls -lh /usr/local/lib64
#  - ls -lh /usr/bin
#  - locate ffmpeg
#  - which ffmpeg
#  - find / | grep ffmpeg
#  - ffmpeg -version
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  #- apt-get install python3-pip
  
  - git submodule update --remote
  #- python3 -m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh
  - python3 -m pip install --ignore-installed -r requirements.txt
  - python3 -m pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye