image: jfloff/alpine-python:3.7

before_script:
  - git submodule update --remote
  - pip install -r requirements.txt
  - pip install -U pytest

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml