image: python:3.10.4-buster

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  #- apk add mpeg libsm6 libxext6 git
  - add-apt-repository universe && sudo apt upgrade
  - apt-get install ffmpeg libsm6 libxext6  -y
  - git submodule update --remote
  - pip install -r requirements.txt
  - pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye