#image: arnoldnico/ifte-ci:py3.10.4-ffmpeg-buster
image: 
  name: arnoldnico/ifte-ci:py3.10.4-ffmpeg-bookworm
  entrypoint: [ '/bin/bash', '-s' ]

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  - python --version
  - pip --version
  - ls -lh /usr/local/bin
  - whereis ffmpeg
  - ffmpeg -version
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  #- apt-get install python3-pip
  
  - git submodule update --remote
  #- python3 -m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh
  - python3 -m pip install --ignore-installed -r requirements.txt
  - python3 -m pip install -U pytest

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye