image: arnoldnico/ifte-ci:py3.10.4-ffmpeg-buster

stages:          # List of stages for jobs, and their order of execution
  - hi
  - test
  - bye

before_script:
  - python --version
  - pip --version
  - ffmpeg -version
  #- apk add mpeg libsm6 libxext6 git
  #- apk update
  #- apk upgrade
  #- apk add --no-cache ffmpeg git
  #- apt-get install python3-pip
#  - apt-get install libqt6
  - git submodule update --remote
  #- python3 -m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -U pytest
  - strip --remove-section=.note.ABI-tag <snip>/.venv/lib/python3.10/site-packages/PySide6/Qt/lib/libQt6Core.so.6
  #- python -c 'import PySide6; print(PySide6.__version__)'
  - ldd <snip>/.venv/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6

hello:
  stage: hi
  script:
    - echo Hello

pytest:
  stage: test
  script:
    - pytest tests
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml

goodbye:
  stage: bye
  script:
    - echo Goodbye